version: 2
jobs:
  s2i:
    docker:
      - image: docker:stable
    working_directory: /opt/app-root/apicast
    environment:
      S2I_VERSION: "1.1.7-226afa1"
    steps:
      - checkout
      - run: apk update && apk add wget make
      - run: travis/install-s2i.sh
      - setup_remote_docker
      - run: export PATH="/root/bin:${PATH}"
      - run: make builder-image
      - run: make test-builder-image gateway-logs --keep-going
      - run: make prove-docker
      - run: make runtime-image
      - run: make test-runtime-image gateway-logs --keep-going
      # - run: make test-doc # TODO: extract this into a docker container or some node container
      - run: make danger
  build:
    docker:
      - image: quay.io/3scale/s2i-openresty-centos7:luarocks-build
        environment:
          TEST_NGINX_BINARY: openresty
      - image: redis:3.2.8-alpine
    working_directory: /opt/app-root/apicast
    steps:
      - checkout
      - restore_cache:
          keys:
            - apicast-v1-{{ checksum "apicast/apicast-0.1-0.rockspec" }}-apicast-rockspec
            - apicast-v1-{{ .Branch }}
            - apicast-v1-master
      - run: luarocks make apicast/*.rockspec
      - save_cache:
          key: apicast-v1-{{ checksum "apicast/apicast-0.1-0.rockspec" }}-apicast-rockspec
          paths:
            - /usr/local/openresty/luajit/share/lua/5.1
            - /usr/local/openresty/luajit/lib64/luarocks/rocks
            - /usr/local/openresty/luajit/lib/lua/5.1
      - restore_cache:
          keys:
            - apicast-v1-{{ checksum "rockspec" }}-rockspec
            - apicast-v1-{{ .Branch }}
            - apicast-v1-master
      - run: luarocks make rockspec
      - save_cache:
          key: apicast-v1-{{ checksum "rockspec" }}-rockspec
          paths:
            - /usr/local/openresty/luajit/share/lua/5.1
            - /usr/local/openresty/luajit/lib64/luarocks/rocks
            - /usr/local/openresty/luajit/lib/lua/5.1
      - run: make busted
      - run: prove # no carton on centos
      - run: make doc

workflows:
  version: 2
  build:
    jobs:
      - build
  s2i:
    jobs:
      - s2i
